title: 106 Lab Guide
description: A lab guide for University of California, Berkeley's 106 robotics series (Electrical Engineering and Computer Science C106A/B, Mechanical Engineering 106). 
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
